### ISSUE TITLE
Conserve screen space while playing text games

### ISSUE THREAD

**Issue by ShinonomeLab** [tonyeung/Stack-Exchange-Chat-Bot#2]
Hangman posts a new message every time somebody guesses a new letter. This takes up a lot of screen space with every new guess. Players can be instructed that they can edit their messages to post new guesses and HoiHoi-san should also edit her updated game state post.

Of course, editing can only be done for 3 minutes, but even so an average game will last about 5 minutes, which means `(1 + number of players) * minutes played / 3` total post count per game, and not `number of guesses * 2` as it is now.

**Comment by tonyeung** [comment]
wrong repo
